services:
  - type: web
    name: momo-optimizer
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: MomoOpti
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "6543"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: APP_KEY
        generateValue: true
